// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	zilliz "github.com/zilliztech/terraform-provider-zillizcloud/client"
)

var _ resource.Resource = &ProjectResource{}
var _ resource.ResourceWithConfigure = &ProjectResource{}
var _ resource.ResourceWithImportState = &ProjectResource{}

const projectResourceMarkdownDescription = "Manages a standard project in Zilliz Cloud.\n" +
	"This resource allows you to create and manage standard projects.\n" +
	"Typical use case: creating projects with specific plan types and region bindings.\n\n" +
	"Project region bindings are append-only. The project API can add regions to a project but cannot remove them, so removing values from `region_ids` returns a Terraform error instead of silently ignoring the change.\n\n" +
	"Project deletion is not yet implemented by the project API. Terraform destroy returns an error and preserves state until project delete support is available."

func NewProjectResource() resource.Resource {
	return &ProjectResource{}
}

type ProjectResource struct {
	client *zilliz.Client
}

type ProjectResourceModel struct {
	Id          types.String `tfsdk:"id"`
	ProjectName types.String `tfsdk:"project_name"`
	Plan        types.String `tfsdk:"plan"`
	RegionIds   types.Set    `tfsdk:"region_ids"`
}

func (r *ProjectResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (r *ProjectResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: projectResourceMarkdownDescription,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: `The unique identifier for the project, automatically generated by the service.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_name": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				MarkdownDescription: `The name of the project to be created. Must be unique within your account.`,
			},
			"plan": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				Default:             stringdefault.StaticString("Enterprise"),
				MarkdownDescription: `The plan type for the project. Valid values are "Standard", "Enterprise", and "BusinessCritical". By default, the plan is "Enterprise".`,
				Validators: []validator.String{
					stringvalidator.OneOf("Standard", "Enterprise", "BusinessCritical"),
				},
			},
			"region_ids": schema.SetAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: `Region IDs to bind to the project. Region IDs are append-only because the project API can add regions but cannot remove them.`,
			},
		},
	}
}

func (r *ProjectResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*zilliz.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider type",
			fmt.Sprintf("Expected *zilliz.Client, got: %T. Please check provider configuration.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *ProjectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	regionIds, regionDiags := stringSetToSlice(ctx, data.RegionIds)
	resp.Diagnostics.Append(regionDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectId, err := r.client.CreateProject(&zilliz.CreateProjectRequest{
		ProjectName: data.ProjectName.ValueString(),
		Plan:        data.Plan.ValueString(),
		Regions:     regionIds,
	})
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to create project",
			fmt.Sprintf("ProjectName: %s, Plan: %s, Region IDs: %v, error: %s", data.ProjectName.ValueString(), data.Plan.ValueString(), regionIds, err.Error()),
		)
		return
	}

	data.Id = types.StringValue(*projectId)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ProjectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	project, err := r.client.GetProjectById(state.Id.ValueString())
	if err != nil {
		// If project not found, remove from state (drift detection)
		resp.State.RemoveResource(ctx)
		return
	}

	state.ProjectName = types.StringValue(project.ProjectName)
	state.Plan = types.StringValue(project.Plan)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ProjectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ProjectResourceModel
	var state ProjectResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only plan can be updated (upgraded)
	if !plan.Plan.Equal(state.Plan) {
		_, err := r.client.UpgradeProjectPlan(state.Id.ValueString(), plan.Plan.ValueString())
		if err != nil {
			resp.Diagnostics.AddError(
				"Failed to upgrade project plan",
				fmt.Sprintf("Project ID: %s, New Plan: %s, error: %s", state.Id.ValueString(), plan.Plan.ValueString(), err.Error()),
			)
			return
		}
		state.Plan = plan.Plan
	}

	addedRegions, removedRegions, regionDiags := diffStringSets(ctx, state.RegionIds, plan.RegionIds)
	resp.Diagnostics.Append(regionDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if len(removedRegions) > 0 {
		resp.Diagnostics.AddError(
			"Project region removal is not supported",
			fmt.Sprintf("Project ID: %s, removed region IDs: %v. The project API only supports appending region IDs; Terraform cannot remove project regions until the API supports removal.", state.Id.ValueString(), removedRegions),
		)
		return
	}

	if len(addedRegions) > 0 {
		regions, err := r.client.AddProjectRegions(state.Id.ValueString(), addedRegions)
		if err != nil {
			resp.Diagnostics.AddError(
				"Failed to add project regions",
				fmt.Sprintf("Project ID: %s, Region IDs: %v, error: %s", state.Id.ValueString(), addedRegions, err.Error()),
			)
			return
		}
		if len(regions) > 0 {
			regionIds, regionDiags := types.SetValueFrom(ctx, types.StringType, regions)
			resp.Diagnostics.Append(regionDiags...)
			if resp.Diagnostics.HasError() {
				return
			}
			state.RegionIds = regionIds
		} else {
			state.RegionIds = plan.RegionIds
		}
	} else {
		state.RegionIds = plan.RegionIds
	}

	state.ProjectName = plan.ProjectName

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ProjectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ProjectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// TODO: Implement project deletion when the Zilliz Cloud project API exposes delete support.
	resp.Diagnostics.AddError(
		"Project delete is not implemented",
		fmt.Sprintf("Project ID: %s. Project delete is not yet implemented in the Zilliz Cloud API, and Terraform destroy will not succeed until project delete support is implemented.", state.Id.ValueString()),
	)
}

func (r *ProjectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID is simply the project ID
	projectId := req.ID

	// Fetch the project to verify it exists and get all attributes
	project, err := r.client.GetProjectById(projectId)
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to import project",
			fmt.Sprintf("Project ID: %s, error: %s", projectId, err.Error()),
		)
		return
	}

	// Set all attributes in state
	var state ProjectResourceModel
	state.Id = types.StringValue(projectId)
	state.ProjectName = types.StringValue(project.ProjectName)
	state.Plan = types.StringValue(project.Plan)
	state.RegionIds = types.SetNull(types.StringType)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func stringSetToSlice(ctx context.Context, value types.Set) ([]string, diag.Diagnostics) {
	var result []string
	var diags diag.Diagnostics
	if value.IsNull() || value.IsUnknown() {
		return result, diags
	}
	diags.Append(value.ElementsAs(ctx, &result, false)...)
	return result, diags
}

func diffStringSets(ctx context.Context, previous, next types.Set) (added []string, removed []string, diags diag.Diagnostics) {
	previousValues, previousDiags := stringSetToSlice(ctx, previous)
	diags.Append(previousDiags...)
	nextValues, nextDiags := stringSetToSlice(ctx, next)
	diags.Append(nextDiags...)
	if diags.HasError() {
		return nil, nil, diags
	}

	previousSeen := make(map[string]struct{}, len(previousValues))
	for _, value := range previousValues {
		previousSeen[value] = struct{}{}
	}
	nextSeen := make(map[string]struct{}, len(nextValues))
	for _, value := range nextValues {
		nextSeen[value] = struct{}{}
		if _, ok := previousSeen[value]; !ok {
			added = append(added, value)
		}
	}
	for _, value := range previousValues {
		if _, ok := nextSeen[value]; !ok {
			removed = append(removed, value)
		}
	}

	return added, removed, diags
}
